### ISSUE TITLE
Rename select Output director (sidecar by default) to Select destination folder for transcoded file(s) and sidecars.

### ISSUE THREAD

**Issue by AnjaMahler** [kieranjol/ffv1-gui#16]

**Comment by kieranjol** [comment]
:+1:

**Comment by kieranjol** [comment]
I like the file(s) touch ;)

**Comment by kieranjol** [comment]
fixed - couldn't fit in the sidecar bit, even though I would have preferred to include it. P.S - I took up your suggestion re tooltips - if you hover over options now a little help bubble pops up. thanks! https://github.com/kieranjol/ffv1-gui/commit/bebea910321a635f2489a1d923f134ea315703b1
